import { execFileSync } from 'node:child_process';
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

function toPascalCase(value: string): string {
	return value
		.split(/[^a-zA-Z0-9]/)
		.filter(Boolean)
		.map((part) => part[0].toUpperCase() + part.slice(1))
		.join('');
}

function runQuicktype(inputFile: string, topLevel: string): string {
	const output = execFileSync(
		'npx',
		[
			'--no-install',
			'quicktype',
			'--lang',
			'ts',
			'--just-types',
			'--alphabetize-properties',
			'--top-level',
			topLevel,
			inputFile
		],
		{ encoding: 'utf8' }
	);

	return output.trim();
}

function indentBlock(text: string, spaces = 2): string {
	const prefix = ' '.repeat(spaces);
	return text
		.split('\n')
		.map((line) => (line.length > 0 ? `${prefix}${line}` : line))
		.join('\n');
}

function main(): void {
	const scriptDir = dirname(fileURLToPath(import.meta.url));
	const repoRoot = resolve(scriptDir, '..');
	const dataDir = join(repoRoot, 'static', 'data');
	const outFile = join(repoRoot, 'src', 'lib', 'datatypes.ts');

	const jsonFiles = readdirSync(dataDir)
		.filter((file) => extname(file) === '.json')
		.sort((a, b) => a.localeCompare(b));

	if (jsonFiles.length === 0) {
		throw new Error(`No JSON files found in ${dataDir}`);
	}

	const generatedBlocks = jsonFiles.map((fileName) => {
		const fileBase = fileName.replace(/\.json$/, '');
		const pascalBase = toPascalCase(fileBase);
		const namespaceName = `${pascalBase}Types`;
		const topLevel = `${pascalBase}Entry`;
		const aliasName = `${pascalBase}Data`;
		const filePath = join(dataDir, fileName);
		const quicktypeOutput = runQuicktype(filePath, topLevel);
		const namespacedOutput = indentBlock(quicktypeOutput, 2);

		return [
			`// Generated from static/data/${fileName}`,
			`export namespace ${namespaceName} {`,
			namespacedOutput,
			`}`,
			`export type ${aliasName} = Record<string, ${namespaceName}.${topLevel}>;`
		].join('\n');
	});

	const fileContent = `// This file is auto-generated by scripts/create_data_types.ts\n// Do not edit manually.\n\n${generatedBlocks.join('\n\n')}`;

	writeFileSync(outFile, `${fileContent}\n`, 'utf8');
	console.log(`Generated ${outFile} from ${jsonFiles.length} JSON files.`);
}

main();
